name: Github Pages Deployment

on:
  push:
    branches: master
  pull_request:
    branches: master
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install and build
        run: |
          echo installing...
          npm install
          echo building...
          npm run build

      - name: deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          branch: gh-pages 
          folder: build
          
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          
